### ISSUE TITLE
Power dropouts in Critical Power calculations, but not in ride analysis

### ISSUE THREAD

**Issue by jrwagz** [mayfield/strava-sauce#3]
Today's ride on Strava has some really strange behavior going on, specifically the numbers used in the critical power calculations have power dropouts, that aren't actually in the real data, thus causing the number to be quite skewed.

![image](https://cloud.githubusercontent.com/assets/498172/13201130/2a8cb182-d819-11e5-9c4e-af500bd78182.png)

Strava URL: http://www.strava.com/activities/498225031/overview

Raw Data in CSV format, from Cyclemeter: http://share.abvio.com/e950412ad87163a9/Cyclemeter-Cycle-20160220-1304.csv

Ride Data in FIT format, from Cyclemeter: http://share.abvio.com/e950412ad87163a9/Cyclemeter-Cycle-20160220-1304.fit

**Comment by mayfield** [comment]
That is strange and unexpected.  Especially considering this section looks like it's longer than 5 mins without drop outs and an avg over 400.. http://www.strava.com/activities/498225031/analysis/1059/1183

**Comment by mayfield** [comment]
I think I know what's going on.  The critical power calculation I use is less forgiving of gaps in recording data.  It makes assumptions that your recording equipment will record one sample per second and treats exceptions to this as zero padding.  See: https://github.com/mayfield/strava-sauce/blob/master/src/lib.js#L234

I assume this was recorded using the equipment your mentioned in your other GPS related issue?  My initial requirements were narrowly defined based on the equipment I use, which is setup to always record 1 sample per second.  Golden Cheetah also makes this recommendation for power meters with tunable power settings.

I'll need to study this particular ride a bit more before I can decide the best course of action.  It might just be increasing max_data_gap, which is currently set here: https://github.com/mayfield/strava-sauce/blob/master/src/lib.js#L143

Cheers.

**Comment by mayfield** [comment]
Here are the gaps > 5 seconds from your particular ride.

[dropouts.txt](https://github.com/mayfield/strava-sauce/files/139851/dropouts.txt)

The median is 7 seconds and mode is 6;  Both are just outside the 5 second max gap in this sample.  So I might just play with making the max gap bigger.  I suppose its main intent was to prevent abuse so I could entertain it being much larger.  Still need to jog my memory about some of this though.

**Comment by jrwagz** [comment]
Thanks @mayfield for looking into this.  You are correct, I used my iPhone6 running the Cyclemeter application to record this data, which is the same as last weeks ride.  This week, I disabled their auto-stop calculations on export so we don't see the GPS strangeness we did last week.

I had assumed that it always recorded every second, I will get in contact with them to see what they expect the recording interval to be.

**Comment by jrwagz** [comment]
Is there a particular reason that you aren't interpolating the values in these cases?  It appears that this is what Strava is doing.

I have done a bit of digging (opened up the database on the backend of Cyclemeter) and found that most samples are stored in the database at 2 second intervals.  (see raw DB export here in csv format)
[sensorData_426.csv.zip](https://github.com/mayfield/strava-sauce/files/140145/sensorData_426.csv.zip)

It looks like I may be able to improve things in my export to potentially avoid this going forward, however you may also want to reconsider using interpolation vs. zero padding.

**Comment by mayfield** [comment]
Hi @jrwagz.  I've not considered any sort of interpolation (yet).  The zero padding is mostly to prevent fraud.  Not necessarily intentional fraud but a case where doing hillclimbs with breaks might result in stupendous CP values even though large chunks of rest was taking place in between.

Given a moment to think about it, my initial worry would be about interpolation being too specific to steady state efforts and it's not clear to me that you gain much by arbitrarily increasing the sample size with interpolated values.  It's possible I'm very wrong.  Just thinking out loud.  

Fun fact, sauce actually overrides the avg calc used in the analysis page, so if it was interpolating before, it's not with sauce installed! :) 

https://github.com/mayfield/strava-sauce/blob/master/src/analysis.js#L401

**Comment by jrwagz** [comment]
So my belief that Strava interpolates the sensor values is based on the visual lines drawn in their graphs, and the fact that the average shown in the ride analysis section was nearly 50w greater than in the critical power section.

That belief is however put in question based on your comment that you override the average value in the ride analysis section.

All this however begs one really big question: If you are in fact overriding the average in the ride analysis section, why doesn't that value match what's shown in the critical power section?  (See screenshot in first post)

**Comment by mayfield** [comment]
Re: the graph.  That makes sense.  I'm not sure exactly how they render dropouts now that you mention that.  I'm tempted to load some crazy data into strava and see what they do when a huge gap occurs between two very high readings.

The analysis avg calc doesn't zero-pad gaps so it can be different than the CP calc method.  It's just an average of the samples for a given selection.  Oddly enough, the reason I override the strava value here was because I could not understand how strava was coming up with their value.  I did fairly extensive comparisons with training peaks wko+ and GC and could not for the life of me figure out how they arrived at their avg power value even with perfect data.  As a result I decided their value may actually be buggy and I replaced it with a dead simple mean calculation.  Doing so made the values nearly identical to what I'd see with those other software packages which have been my gold standard for much of my cycling analysis. 

Keep in mind all my work has been with 2 power meters which generally provided highly predictable 1 second interval recordings.  The only time I have gaps in my data is when I actually stop riding, so the bug being discussed here is still valid.  Cyclemeter uses much more variable recording intervals than I had ever anticipated. 

Good news though; Just changing the max gap to 15 seconds fixes your initial issue as I suspected it might.  You can try it yourself by installing from a github clone.  I may do this change for now and release and then study the issue more.
